---
apiVersion: v1
kind: Service
metadata:
  name: authz
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    name: authz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
spec:
  replicas: 1
  selector:
    matchLabels:
      name: authz
  template:
    metadata:
      labels:
        name: authz
    spec:
      containers:
      - name: app
        image: 192.168.0.164:15000/tucom/authz
        args: ["-config=/etc/authz/config.yaml"]
        imagePullPolicy: Always
        #resources:
          #requests:
            #cpu: "0.1"
            #memory: "256Mi"
          #limits:
            #cpu: "0.2"
            #memory: "1Gi"
        ports:
          - containerPort: 50051
        volumeMounts:
          - mountPath: /etc/authz/config.yaml
            name: authz
            subPath: config.yaml
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      volumes:
        - name: authz
          configMap:
            name: authz-configmap
            items:
              - key: authz_config
                path: authz.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-configmap
data:
  authz_config: |-
    server:
      grpc: localhost:50051
    database:
      host: 192.168.0.164
      port: 15432
      db_name: authnz
      user: authnz
      pass: 19950416

