// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/authnz.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthNZClient is the client API for AuthNZ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthNZClient interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type authNZClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthNZClient(cc grpc.ClientConnInterface) AuthNZClient {
	return &authNZClient{cc}
}

func (c *authNZClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, "/com.github.dlshle.authnz.AuthNZ/authorize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthNZServer is the server API for AuthNZ service.
// All implementations must embed UnimplementedAuthNZServer
// for forward compatibility
type AuthNZServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	mustEmbedUnimplementedAuthNZServer()
}

// UnimplementedAuthNZServer must be embedded to have forward compatible implementations.
type UnimplementedAuthNZServer struct {
}

func (UnimplementedAuthNZServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAuthNZServer) mustEmbedUnimplementedAuthNZServer() {}

// UnsafeAuthNZServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthNZServer will
// result in compilation errors.
type UnsafeAuthNZServer interface {
	mustEmbedUnimplementedAuthNZServer()
}

func RegisterAuthNZServer(s grpc.ServiceRegistrar, srv AuthNZServer) {
	s.RegisterService(&AuthNZ_ServiceDesc, srv)
}

func _AuthNZ_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthNZServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dlshle.authnz.AuthNZ/authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthNZServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthNZ_ServiceDesc is the grpc.ServiceDesc for AuthNZ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthNZ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.dlshle.authnz.AuthNZ",
	HandlerType: (*AuthNZServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "authorize",
			Handler:    _AuthNZ_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authnz.proto",
}
